version: "3"

services:
  
  server:
    image: server
    command: npm run dev
    build: server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    container_name: server
    ports:
      - 3000:3000
    environment:
      ENVIRONMENT: development
    depends_on:
      - psqldb

  psqldb:
    image: postgres:11-alpine
    container_name: psqldb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cmov
      - POSTGRES_PASSWORD=cmov
      - POSTGRES_DB=cmov

  pgadmin:
    image: thajeztah/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:5050
    depends_on:
      - psqldb
